"""
Domain Templates for Seedling.

Pre-defined domains with seed instructions for various technical areas.
Each domain contains a description, list of topics, and seed instructions
that can be used to generate synthetic training data.

This module provides two types of templates:
1. Technical Domains (DOMAIN_TEMPLATES) - DevOps, Cloud, Security, etc.
2. Role-based Templates (via roles.py) - Customer Support, Data Analyst, etc.

For role-based instruction sets that may be replaced by AI, see the
roles.py module and config/roles.yaml.
"""

from __future__ import annotations

from typing import Any

from .roles import (
    get_all_roles_as_domain_templates,
    get_role_manager,
    get_role_seeds,
)

DOMAIN_TEMPLATES = {
    "DevOps": {
        "description": "Infrastructure as Code, CI/CD, Containerization, Orchestration",
        "topics": [
            "Terraform",
            "Ansible",
            "Kubernetes",
            "Docker",
            "Helm",
            "GitLab CI",
            "GitHub Actions",
            "Jenkins",
            "ArgoCD",
            "Prometheus",
            "Grafana",
            "ELK Stack",
        ],
        "seeds": [
            "Write a Terraform configuration for an AWS S3 bucket with versioning and encryption",
            "Create an Ansible playbook that installs Docker on Ubuntu servers",
            "Write a Kubernetes deployment for a Node.js application with 3 replicas",
            "Create a GitHub Actions pipeline that runs tests and builds a Docker image",
            "Write a Helm chart for a Redis installation with persistence",
            "Create a Docker Compose file for a LAMP stack",
            "Write a Prometheus alert for high CPU usage",
            "Create a GitLab CI pipeline that automatically creates Terraform plans",
            "Write a Kubernetes ConfigMap that loads environment variables from a .env file",
            "Create an Ansible role for Nginx configuration with SSL",
            "Write an ArgoCD application manifest for GitOps deployment",
            "Create a Grafana dashboard JSON for container metrics",
            "Write a Terraform module for a VPC with public and private subnets",
            "Create a Kubernetes CronJob that creates daily database backups",
            "Write a Jenkins pipeline that supports multi-branch builds",
        ],
    },
    "SysAdmin": {
        "description": "Windows/Linux Administration, Scripting, Identity Management",
        "topics": [
            "PowerShell",
            "Bash",
            "Active Directory",
            "Entra ID",
            "Intune",
            "SCCM",
            "Group Policy",
            "Linux Administration",
            "Systemd",
            "Networking",
            "Storage",
            "Backup",
        ],
        "seeds": [
            "Write a PowerShell script that exports all disabled users from Active Directory",
            "Create a Bash script that deletes log files older than 30 days",
            "Write a PowerShell script that lists Microsoft 365 licenses for all users",
            "Create a Bash script that monitors disk space and sends an email at 90%",
            "Write a PowerShell script that retrieves Intune device compliance status",
            "Create a Group Policy that blocks USB storage devices",
            "Write a Bash script that automatically renews SSL certificates with Certbot",
            "Create a PowerShell script that lists Exchange Online mailbox sizes",
            "Write a systemd service file for a Python application",
            "Create a PowerShell script that exports Azure AD Conditional Access policies",
            "Write a Bash script that creates a MySQL dump and uploads to S3",
            "Create a PowerShell script that searches Windows Event Logs for errors",
            "Write a Bash script that analyzes Nginx access logs and shows top IPs",
            "Create a PowerShell script that uses Microsoft Graph API to create users",
            "Write a Bash script that rotates SSH keys on multiple servers",
        ],
    },
    "Cloud": {
        "description": "AWS, Azure, GCP Cloud Services and Architectures",
        "topics": [
            "AWS",
            "Azure",
            "GCP",
            "IAM",
            "Networking",
            "Serverless",
            "Lambda",
            "Functions",
            "Storage",
            "Database",
            "VPC",
            "Load Balancing",
            "CDN",
        ],
        "seeds": [
            "Write an AWS Lambda function that processes S3 events and stores in DynamoDB",
            "Create an Azure Function that processes Blob Storage uploads",
            "Write a CloudFormation template for an Auto Scaling Group",
            "Create a GCP Cloud Run service manifest",
            "Write an AWS IAM policy for minimal S3 permissions",
            "Create an Azure Resource Manager template for a Virtual Network",
            "Write an AWS CDK script for a REST API with API Gateway and Lambda",
            "Create a GCP IAM binding for service account impersonation",
            "Write an AWS Step Functions definition for an approval workflow",
            "Create an Azure Logic App for email-to-ticket automation",
            "Write a CloudWatch alarm configuration for Lambda errors",
            "Create a GCP Cloud Function that processes Pub/Sub messages",
            "Write an AWS EventBridge rule for scheduled Lambda invocations",
            "Create an Azure Key Vault access policy",
            "Write a Terraform script for AWS RDS with Multi-AZ",
        ],
    },
    "Security": {
        "description": "Information Security, Compliance, Hardening",
        "topics": [
            "ISMS",
            "ISO 27001",
            "IT-Grundschutz",
            "GDPR",
            "Hardening",
            "Penetration Testing",
            "Incident Response",
            "Vulnerability Management",
            "SIEM",
            "Zero Trust",
        ],
        "seeds": [
            "Write a security policy for password complexity according to ISO 27001",
            "Create a checklist for Linux server hardening according to CIS Benchmarks",
            "Write a PowerShell script that checks Windows Security Baseline",
            "Create an incident response procedure for ransomware attacks",
            "Write a Bash script that scans open ports and documents them",
            "Create a GDPR-compliant data processing agreement template",
            "Write a Python script that checks SSL certificates for expiration dates",
            "Create a Zero Trust architecture design document outline",
            "Write a Splunk query for failed login attempts detection",
            "Create a vulnerability assessment report template",
            "Write a PowerShell script that analyzes Azure AD sign-in logs",
            "Create a business continuity plan outline according to ISO 22301",
            "Write a Bash script that documents firewall rules",
            "Create a security awareness training agenda",
            "Write a Python script that uses the HIBP API for email leak checks",
        ],
    },
    "Database": {
        "description": "SQL, NoSQL, Data Engineering, ETL",
        "topics": [
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis",
            "Elasticsearch",
            "SQL",
            "ETL",
            "Data Modeling",
            "Backup",
            "Replication",
            "Performance Tuning",
        ],
        "seeds": [
            "Write a PostgreSQL query that finds the top 10 slowest queries",
            "Create a MongoDB aggregation pipeline for user activity analytics",
            "Write a SQL script that documents foreign key constraints",
            "Create a Python ETL script that loads CSV into PostgreSQL",
            "Write a MySQL stored procedure for audit logging",
            "Create a Redis caching pattern for session management",
            "Write a SQL query that shows database sizes for all tables",
            "Create a PostgreSQL backup script with pg_dump and rotation",
            "Write a MongoDB index optimization script",
            "Create a SQL migration script for schema changes",
            "Write a Python script that manages Elasticsearch indices",
            "Create a PostgreSQL replication configuration for read replicas",
            "Write a SQL query that finds dead tuples in PostgreSQL",
            "Create a MySQL Performance Schema query for lock analysis",
            "Write a Python script that pools database connections",
        ],
    },
    "Code": {
        "description": "General Programming in Various Languages",
        "topics": [
            "Python",
            "TypeScript",
            "JavaScript",
            "Rust",
            "Go",
            "REST APIs",
            "Testing",
            "Design Patterns",
            "Refactoring",
            "Documentation",
            "Code Review",
        ],
        "seeds": [
            "Write a Python class for a repository pattern with SQLAlchemy",
            "Create a TypeScript utility function for deep object merging",
            "Write a Go HTTP handler with proper error handling",
            "Create a Python decorator for retry logic with exponential backoff",
            "Write a Rust function for safe file I/O with error handling",
            "Create a TypeScript interface for a REST API response",
            "Write a Python unit test for an async function with pytest",
            "Create a Go struct with JSON tags and validation",
            "Write a Python function that validates environment variables",
            "Create a TypeScript generic for type-safe API calls",
            "Write a Python context manager for database transactions",
            "Create a Go middleware for request logging",
            "Write a Python script that generates OpenAPI specs",
            "Create a TypeScript enum with associated utility functions",
            "Write a Rust CLI application with clap for argument parsing",
        ],
    },
    "Networking": {
        "description": "Network Administration, Protocols, Routing, Firewalls",
        "topics": [
            "TCP/IP",
            "DNS",
            "DHCP",
            "VPN",
            "Firewall",
            "Load Balancer",
            "BGP",
            "VLAN",
            "SDN",
            "IPv6",
            "Wireshark",
            "iptables",
            "pfSense",
        ],
        "seeds": [
            "Write a Bash script that analyzes all active network connections with netstat",
            "Create an iptables configuration for a web server with rate limiting",
            "Write a Python script that queries DNS records and documents them",
            "Create a pfSense firewall rule documentation template",
            "Write a PowerShell script that exports Windows Firewall rules",
            "Create a Bash script that monitors network latency to multiple hosts",
            "Write an Nginx configuration for TCP load balancing",
            "Create a Python script that performs subnet calculations",
            "Write a Bash script that creates VLAN configurations on Linux",
            "Create a VPN configuration for WireGuard with multiple peers",
            "Write a Python script that analyzes Wireshark PCAP files",
            "Create an Ansible playbook for configuring network interfaces",
            "Write a Bash script that generates IPv6 addresses for a subnet",
            "Create an HAProxy configuration for HTTPS termination",
            "Write a Python script that retrieves SNMP data from switches",
        ],
    },
    "DataScience": {
        "description": "Machine Learning, Data Analysis, Visualization, Statistics",
        "topics": [
            "Pandas",
            "NumPy",
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "Jupyter",
            "Matplotlib",
            "Seaborn",
            "Feature Engineering",
            "Model Training",
            "Data Cleaning",
            "Statistical Analysis",
        ],
        "seeds": [
            "Write a Python script that cleans a DataFrame with Pandas and handles null values",
            "Create a Jupyter notebook cell for exploratory data analysis with visualizations",
            "Write a Python function for feature scaling with Scikit-learn",
            "Create a Python script that trains and evaluates a Random Forest classifier",
            "Write a Python function for cross-validation with multiple metrics",
            "Create a Matplotlib dashboard with multiple subplots for data visualization",
            "Write a Python script that performs outlier detection with IQR",
            "Create a Python class for a custom transformer in Scikit-learn pipelines",
            "Write a Python script that analyzes time series data with rolling windows",
            "Create a PyTorch neural network for binary classification",
            "Write a Python function for one-hot encoding with Pandas",
            "Create a Python script that performs hyperparameter tuning with GridSearchCV",
            "Write a Seaborn visualization for correlation heatmaps",
            "Create a Python script that preprocesses text data for NLP",
            "Write a Python function for train-test split with stratification",
        ],
    },
    "Frontend": {
        "description": "Web Development, UI/UX, Frameworks, Accessibility",
        "topics": [
            "React",
            "Vue",
            "Angular",
            "TypeScript",
            "CSS",
            "Tailwind",
            "Responsive Design",
            "Accessibility",
            "Testing",
            "State Management",
            "Web Performance",
            "Progressive Web Apps",
        ],
        "seeds": [
            "Write a React component with useState and useEffect for data fetching",
            "Create a Vue 3 Composition API component with reactive data",
            "Write a TypeScript React custom hook for form validation",
            "Create a CSS Grid layout for a responsive dashboard",
            "Write a React component with Tailwind CSS for a card list",
            "Create a Vue Router configuration with navigation guards",
            "Write a React Context provider for global state management",
            "Create an Angular service class for HTTP requests with error handling",
            "Write a React component that follows accessibility (ARIA) best practices",
            "Create a Jest test for a React component with Testing Library",
            "Write a CSS animation for a loading spinner",
            "Create a React lazy loading implementation for code splitting",
            "Write a Progressive Web App manifest file with service worker",
            "Create a Storybook story for a button component",
            "Write a React error boundary component with fallback UI",
        ],
    },
    "Mobile": {
        "description": "Mobile App Development, iOS, Android, Cross-Platform",
        "topics": [
            "React Native",
            "Flutter",
            "Swift",
            "Kotlin",
            "iOS",
            "Android",
            "Mobile UI",
            "Push Notifications",
            "App Store",
            "Mobile Security",
            "Offline Storage",
            "Gestures",
        ],
        "seeds": [
            "Write a React Native component with FlatList for infinite scrolling",
            "Create a Flutter widget for a custom bottom navigation bar",
            "Write a Swift function for Core Data persistence",
            "Create a Kotlin class for Room database entity and DAO",
            "Write a React Native custom hook for AsyncStorage management",
            "Create a Flutter BLoC pattern for state management",
            "Write a Swift function for push notification handling",
            "Create a Kotlin function for Retrofit API calls with coroutines",
            "Write a React Native component for gesture handling with PanResponder",
            "Create a Flutter widget for responsive layout with MediaQuery",
            "Write a Swift function for Keychain secure storage",
            "Create a Kotlin function for biometric authentication",
            "Write a React Native navigation setup with React Navigation",
            "Create a Flutter widget for image caching and loading states",
            "Write a Swift function for background task scheduling",
        ],
    },
    "QA": {
        "description": "Quality Assurance, Test Automation, Performance Testing",
        "topics": [
            "Selenium",
            "Cypress",
            "Playwright",
            "Jest",
            "pytest",
            "Load Testing",
            "API Testing",
            "Test Planning",
            "BDD",
            "CI/CD Testing",
            "Mobile Testing",
            "Accessibility Testing",
        ],
        "seeds": [
            "Write a Cypress E2E test for a login flow",
            "Create a Playwright test script for cross-browser testing",
            "Write a pytest test with fixtures and parametrization",
            "Create a Selenium Page Object Model for a web application",
            "Write a k6 load test script for API performance testing",
            "Create a Jest mock implementation for external services",
            "Write a Robot Framework test case for keyword-driven testing",
            "Create a Postman collection script for API test automation",
            "Write a pytest test with mocking of database connections",
            "Create a Cypress custom command for reusable actions",
            "Write a JMeter test plan for stress testing",
            "Create a BDD scenario with Gherkin syntax for user stories",
            "Write a Playwright test for accessibility checks with axe-core",
            "Create a pytest plugin for custom test reporting",
            "Write a Selenium Grid configuration for parallel tests",
        ],
    },
    "MLOps": {
        "description": "Machine Learning Operations, Model Deployment, Feature Stores",
        "topics": [
            "MLflow",
            "Kubeflow",
            "Feature Store",
            "Model Registry",
            "Model Serving",
            "A/B Testing",
            "Model Monitoring",
            "Data Versioning",
            "DVC",
            "Experiment Tracking",
        ],
        "seeds": [
            "Write an MLflow experiment tracking script for model training",
            "Create a Kubeflow pipeline for automated ML training",
            "Write a Python script for Feature Store integration with Feast",
            "Create a Docker container for model serving with FastAPI",
            "Write a DVC pipeline for data versioning and reproducibility",
            "Create a Python script for Model Registry with MLflow",
            "Write a Kubernetes deployment for ML model inference",
            "Create a Python script for A/B testing of ML models",
            "Write a monitoring dashboard for model performance metrics",
            "Create a Python script for automatic model retraining",
            "Write an Airflow DAG for ML pipeline orchestration",
            "Create a Python script for feature engineering pipeline",
            "Write a Terraform script for SageMaker endpoint deployment",
            "Create a Python script for data drift detection",
            "Write a GitHub Actions workflow for ML CI/CD pipeline",
        ],
    },
    "API": {
        "description": "API Design, REST, GraphQL, gRPC, Documentation",
        "topics": [
            "REST",
            "GraphQL",
            "gRPC",
            "OpenAPI",
            "Swagger",
            "API Gateway",
            "Rate Limiting",
            "Authentication",
            "Versioning",
            "Webhooks",
            "API Testing",
        ],
        "seeds": [
            "Write a FastAPI route with Pydantic validation and response models",
            "Create a GraphQL schema with queries and mutations",
            "Write a gRPC service definition with Protocol Buffers",
            "Create an OpenAPI 3.0 specification for a User API",
            "Write an Express.js middleware for API rate limiting",
            "Create a Python script for JWT token validation",
            "Write a FastAPI dependency for database session management",
            "Create a GraphQL resolver with DataLoader for N+1 optimization",
            "Write an API versioning strategy with URL prefixes",
            "Create a webhook handler with signature verification",
            "Write a FastAPI exception handler for consistent error responses",
            "Create a gRPC client with retry logic and timeout handling",
            "Write a Swagger UI configuration with custom branding",
            "Create a Python script for API health check endpoints",
            "Write a GraphQL subscription for real-time updates",
        ],
    },
    "Docker": {
        "description": "Docker Containers, Images, Dockerfile, Registry, Networking",
        "topics": [
            "Dockerfile",
            "Docker Build",
            "Docker Run",
            "Docker Images",
            "Docker Volumes",
            "Docker Networks",
            "Docker Registry",
            "Multi-Stage Builds",
            "Container Debugging",
            "Docker Logs",
            "Docker Exec",
            "Docker Prune",
            "Health Checks",
            "Environment Variables",
            "Docker Secrets",
        ],
        "seeds": [
            "Write a Dockerfile for a Python Flask application with multi-stage build",
            "Create a Docker command that deletes all stopped containers",
            "Write a Dockerfile for a Node.js application with npm ci and non-root user",
            "Create a Docker run command with volume mounts and port mappings",
            "Write a Dockerfile with health check for an Nginx web server",
            "Create a Docker command that shows logs from multiple containers simultaneously",
            "Write a Dockerfile for a Go application with scratch base image",
            "Create a Docker build command with build args and cache management",
            "Write a Docker command that opens a shell into a running container",
            "Create a Dockerfile for a Java Spring Boot application with JRE runtime",
            "Write a Docker command that cleans up all unused images and volumes",
            "Create a Docker network command for an isolated bridge network",
            "Write a Dockerfile with ENTRYPOINT and CMD combination for flexible starts",
            "Create a Docker command that monitors container resource usage",
            "Write a Dockerfile for a Rust application with cargo build --release",
        ],
    },
    "DockerCompose": {
        "description": "Docker Compose Multi-Container Orchestration, Services, Networks, Volumes",
        "topics": [
            "docker-compose.yml",
            "Services",
            "Networks",
            "Volumes",
            "Environment Files",
            "Depends On",
            "Health Checks",
            "Profiles",
            "Build Context",
            "Replicas",
            "Resource Limits",
            "Secrets",
            "Override Files",
            "Docker Compose Watch",
            "Service Discovery",
        ],
        "seeds": [
            "Write a docker-compose.yml for a LAMP stack with MySQL and phpMyAdmin",
            "Create a Docker Compose configuration with health checks and depends_on",
            "Write a docker-compose.yml for a microservices architecture with API gateway",
            "Create a Docker Compose configuration with named volumes for persistence",
            "Write a docker-compose.yml with environment file and variable substitution",
            "Create a Docker Compose configuration for ELK stack with Elasticsearch and Kibana",
            "Write a docker-compose.yml with build context and multi-stage Dockerfile",
            "Create a Docker Compose configuration with resource limits for CPU and memory",
            "Write a docker-compose.yml for Redis cluster with multiple replicas",
            "Create a Docker Compose configuration with custom networks and aliases",
            "Write a docker-compose.yml with profiles for dev and production environments",
            "Create a Docker Compose override file for local development",
            "Write a docker-compose.yml for PostgreSQL with automatic backup service",
            "Create a Docker Compose configuration with Traefik reverse proxy and SSL",
            "Write a docker-compose.yml with Docker Compose Watch for hot reload",
        ],
    },
    "Bash": {
        "description": "Shell Scripting, Command Line Tools, Text Processing, Automation",
        "topics": [
            "Bash Scripting",
            "Shell Variables",
            "Control Flow",
            "Functions",
            "Pipes",
            "Redirection",
            "Process Management",
            "Text Processing",
            "File Operations",
            "Error Handling",
            "Subshells",
            "Arrays",
            "Parameter Expansion",
            "Here Documents",
            "Signal Handling",
        ],
        "seeds": [
            "Write a Bash script that lists files recursively sorted by size",
            "Create a Bash script with functions for colored terminal output",
            "Write a Bash script that parses arguments with getopts",
            "Create a Bash script that performs parallel downloads with background jobs",
            "Write a Bash script that parses a configuration file and sets variables",
            "Create a Bash script with error handling and trap for cleanup",
            "Write a Bash script that rotates and compresses log files",
            "Create a Bash script that monitors processes by memory usage",
            "Write a Bash script with here document for multi-line SQL queries",
            "Create a Bash script that filters files by date and moves them",
            "Write a Bash script that watches a directory for changes",
            "Create a Bash script with arrays for batch processing of files",
            "Write a Bash script that reads stdin and processes line by line",
            "Create a Bash script with lockfile for single-instance execution",
            "Write a Bash script that loads environment variables from .env file",
        ],
    },
    "SSH": {
        "description": "SSH Connections, Key Management, Tunneling, Remote Execution",
        "topics": [
            "SSH Keys",
            "SSH Config",
            "SSH Tunnel",
            "Port Forwarding",
            "Jump Hosts",
            "SSH Agent",
            "SCP",
            "SFTP",
            "Remote Commands",
            "Known Hosts",
            "Host Key Verification",
            "ProxyJump",
            "ControlMaster",
            "SSH Escape Sequences",
            "Key Rotation",
        ],
        "seeds": [
            "Write an SSH command for local port forwarding to a database",
            "Create an SSH config file with multiple hosts and ProxyJump",
            "Write an SSH command that executes remote commands on multiple servers",
            "Create a Bash script that generates SSH keys and distributes them to servers",
            "Write an SSH tunnel command for dynamic SOCKS proxy",
            "Create an SSH config with ControlMaster for connection multiplexing",
            "Write an SCP command for recursive copying with bandwidth limit",
            "Create a Bash script that configures SSH agent with key timeout",
            "Write an SSH command for reverse port forwarding",
            "Create an SSH config with different keys per host",
            "Write an SSH command that connects via jump host",
            "Create a Bash script that manages SSH host keys in known_hosts",
            "Write an SFTP batch command for automated file transfers",
            "Create an SSH command with pseudo-terminal for interactive sessions",
            "Write a Bash script that monitors SSH connections with timeout",
        ],
    },
    "Curl": {
        "description": "HTTP Requests, API Testing, Downloads, Authentication",
        "topics": [
            "GET Requests",
            "POST Requests",
            "Headers",
            "Authentication",
            "JSON Data",
            "File Upload",
            "Cookies",
            "SSL/TLS",
            "Timeouts",
            "Retry Logic",
            "Output Formatting",
            "Follow Redirects",
            "Rate Limiting",
            "Proxy",
            "Debug Mode",
        ],
        "seeds": [
            "Write a curl command for POST request with JSON body and headers",
            "Create a curl command for API authentication with bearer token",
            "Write a curl command that shows response headers and body separately",
            "Create a curl command for file upload with multipart/form-data",
            "Write a curl command with retry logic and exponential backoff",
            "Create a curl command for download with progress display and resume",
            "Write a curl command for basic authentication with URL encoding",
            "Create a curl command that saves and reuses cookies",
            "Write a curl command with client certificate for mTLS",
            "Create a curl command for GraphQL query with variables",
            "Write a curl command with timeout and connection retry",
            "Create a curl command that measures response time and HTTP status",
            "Write a curl command for PUT request with file content",
            "Create a curl command with proxy and proxy authentication",
            "Write a curl command for parallel requests with xargs",
        ],
    },
    "Ripgrep": {
        "description": "Fast Text Search, Regex Patterns, Code Search, Filtering",
        "topics": [
            "Pattern Matching",
            "Regex",
            "File Type Filtering",
            "Context Lines",
            "Ignore Patterns",
            "Case Sensitivity",
            "Word Boundaries",
            "Multiline",
            "Replace Mode",
            "JSON Output",
            "Glob Patterns",
            "Hidden Files",
            "Binary Files",
            "Count Mode",
            "Files With Matches",
        ],
        "seeds": [
            "Write an rg command that searches for a pattern in specific file types",
            "Create an rg command with context lines before and after the match",
            "Write an rg command for case-insensitive search with word boundaries",
            "Create an rg command that only lists filenames with matches",
            "Write an rg command with regex for IP addresses in log files",
            "Create an rg command that ignores specific directories",
            "Write an rg command for multiline pattern matching",
            "Create an rg command with JSON output for further processing",
            "Write an rg command that counts matches and groups by file",
            "Create an rg command with glob pattern for specific paths",
            "Write an rg command that also searches in hidden files and directories",
            "Create an rg command with replace mode for text substitution",
            "Write an rg command for searching TODO and FIXME comments",
            "Create an rg command with type-add for custom file types",
            "Write an rg command that captures and displays regex groups",
        ],
    },
    "Cat": {
        "description": "File Display, Concatenation, Text Transformation, Pipe Operations",
        "topics": [
            "File Display",
            "Concatenation",
            "Line Numbers",
            "Non-Printing Characters",
            "Heredoc",
            "Pipe Operations",
            "File Creation",
            "Tab Display",
            "End of Line Markers",
            "Squeeze Blank Lines",
            "Binary View",
            "Multiple Files",
            "Standard Input",
            "Reverse Output",
            "Pagination",
        ],
        "seeds": [
            "Write a cat command that displays multiple files with line numbers",
            "Create a cat command with here document for multi-line file creation",
            "Write a cat command that makes non-printing characters visible",
            "Create a cat command combined with grep for filtered output",
            "Write a cat command that shows tabs as ^I and line endings as $",
            "Create a cat command for concatenating split files",
            "Write a cat command with pipe to wc for line statistics",
            "Create a cat command that compresses consecutive blank lines",
            "Write a cat command combined with head and tail for file excerpts",
            "Create a cat command with tee for simultaneous display and save",
            "Write a cat command for binary files with hexdump pipe",
            "Create a cat command that combines stdin with files",
            "Write a cat command with sort and uniq for deduplicated output",
            "Create a cat command combined with sed for text transformation",
            "Write a cat command with nl for continuous numbering across files",
        ],
    },
    "Files": {
        "description": "File Formats, Metadata, Encoding, Conversion, Analysis",
        "topics": [
            "File Formats",
            "MIME Types",
            "Metadata",
            "Encoding",
            "File Headers",
            "Magic Bytes",
            "Checksums",
            "Compression",
            "Archive Formats",
            "File Parsing",
            "Binary Analysis",
            "Text Encoding",
            "File Validation",
            "Format Conversion",
            "File Structure",
        ],
        "seeds": [
            "Write a Python script that analyzes MIME type and magic bytes of a file",
            "Create a Bash script that extracts file metadata with exiftool and outputs as JSON",
            "Write a Python script that detects and converts different text encodings",
            "Create a Python script that unpacks ZIP archives and documents the structure",
            "Write a Bash script that calculates and verifies checksums for files",
            "Create a Python script that extracts PDF metadata and text content",
            "Write a Python script that parses Office documents and exports content as Markdown",
            "Create a Bash script that analyzes file headers and performs format validation",
            "Write a Python script that validates and transforms XML and JSON files",
            "Create a Python script that detects and parses CSV files with different delimiters",
            "Write a Bash script that detects compressed files and optimally decompresses them",
            "Create a Python script that analyzes binary files hexadecimally and finds patterns",
            "Write a Python script that checks file integrity and detects corruption",
            "Create a Bash script that finds file duplicates based on content hash",
            "Write a Python script that extracts embedded files from containers",
        ],
    },
    "Images": {
        "description": "Image Processing, Analysis, OCR, Metadata, Format Conversion",
        "topics": [
            "Image Formats",
            "EXIF Metadata",
            "OCR",
            "Image Analysis",
            "Color Spaces",
            "Resolution",
            "Compression",
            "Thumbnails",
            "Image Recognition",
            "Face Detection",
            "Object Detection",
            "Image Comparison",
            "Watermarks",
            "Steganography",
            "Image Optimization",
        ],
        "seeds": [
            "Write a Python script that performs OCR with Tesseract and extracts text from images",
            "Create a Python script that analyzes EXIF metadata and extracts GPS coordinates",
            "Write a Bash script that batch-converts and optimizes images with ImageMagick",
            "Create a Python script that analyzes image content with OpenCV and detects objects",
            "Write a Python script that analyzes screenshots and identifies UI elements",
            "Create a Python script that compares images for duplicates with perceptual hashing",
            "Write a Bash script that generates thumbnails in various sizes",
            "Create a Python script that extracts and analyzes color palettes from images",
            "Write a Python script that recognizes diagrams and charts in images and extracts data",
            "Create a Python script that evaluates image quality and detects compression artifacts",
            "Write a Python script that detects faces in images and anonymizes them",
            "Create a Bash script that validates image formats and identifies corrupt files",
            "Write a Python script that analyzes text overlays and watermarks in images",
            "Create a Python script that generates image-to-text descriptions with Vision API",
            "Write a Python script that decodes QR codes and barcodes in images",
        ],
    },
    "Audio": {
        "description": "Audio Processing, Transcription, Analysis, Format Conversion",
        "topics": [
            "Audio Formats",
            "Transcription",
            "Speech Recognition",
            "Audio Metadata",
            "Waveform Analysis",
            "Spectrograms",
            "Noise Reduction",
            "Audio Compression",
            "Voice Detection",
            "Music Analysis",
            "Audio Segmentation",
            "Pitch Detection",
            "Sample Rate",
            "Bit Depth",
            "Audio Normalization",
        ],
        "seeds": [
            "Write a Python script that performs audio transcription with Whisper",
            "Create a Python script that extracts and edits audio metadata with mutagen",
            "Write a Bash script that batch-converts audio files with ffmpeg",
            "Create a Python script that detects voice activity in audio files and segments them",
            "Write a Python script that generates spectrograms and visually analyzes audio",
            "Create a Python script that normalizes volume and improves audio quality",
            "Write a Python script that performs speaker diarization and separates speakers",
            "Create a Bash script that extracts audio streams from video files",
            "Write a Python script that analyzes music tempo and beats",
            "Create a Python script that checks audio files for silence and splits them",
            "Write a Python script that detects and classifies background noise",
            "Create a Python script that generates subtitles from audio with timestamps",
            "Write a Bash script that analyzes audio quality and recommends bitrate",
            "Create a Python script that performs audio fingerprinting for duplicate detection",
            "Write a Python script that analyzes emotions and sentiment in speech",
        ],
    },
    "Video": {
        "description": "Video Processing, Analysis, Transcription, Frame Extraction",
        "topics": [
            "Video Formats",
            "Codecs",
            "Frame Extraction",
            "Video Metadata",
            "Transcoding",
            "Scene Detection",
            "Object Tracking",
            "Video OCR",
            "Subtitle Extraction",
            "Video Thumbnails",
            "Motion Detection",
            "Video Quality",
            "Streaming Formats",
            "Video Segmentation",
            "Content Analysis",
        ],
        "seeds": [
            "Write a Python script that extracts keyframes from videos and analyzes them",
            "Create a Bash script that transcodes and compresses videos with ffmpeg",
            "Write a Python script that detects scene changes and segments video",
            "Create a Python script that extracts or generates subtitles from videos",
            "Write a Python script that reads video metadata and displays codec info",
            "Create a Python script that generates thumbnails at specific timestamps",
            "Write a Bash script that converts videos to streaming formats like HLS",
            "Create a Python script that detects motion in videos and marks timestamps",
            "Write a Python script that extracts text and overlays from video frames via OCR",
            "Create a Python script that analyzes video quality and recommends encoding",
            "Write a Python script that transcribes audio track and synchronizes with video",
            "Create a Bash script that concatenates video clips and adds transitions",
            "Write a Python script that tracks faces in videos and outputs timecodes",
            "Create a Python script that describes video content with vision-language models",
            "Write a Python script that detects video duplicates based on visual hashing",
        ],
    },
    "UV": {
        "description": "Modern Python Package Management with uv, Containerization, Dependency Resolution",
        "topics": [
            "uv",
            "pip",
            "pyproject.toml",
            "Dependency Management",
            "Virtual Environments",
            "Lock Files",
            "Container Python",
            "Multi-Stage Builds",
            "Package Publishing",
            "Development Dependencies",
            "Reproducible Builds",
            "Cache Optimization",
            "Python Version Management",
            "Workspace Management",
            "Tool Installation",
        ],
        "seeds": [
            "Write a Dockerfile that uses uv for fast Python dependency installation",
            "Create a pyproject.toml with uv for a modern Python project",
            "Write a multi-stage Dockerfile that uses uv sync for minimal container size",
            "Create a Bash script that uses uv for development environment setup",
            "Write a Dockerfile that optimally uses uv cache for Docker layer caching",
            "Create a GitHub Actions pipeline that uses uv for fast CI/CD builds",
            "Write a uv command that installs production dependencies without dev dependencies",
            "Create a Dockerfile that pins and installs Python version with uv python",
            "Write a Bash script that uses uv lock for reproducible dependency resolution",
            "Create a Dockerfile that uses uv tool install for CLI tools in container",
            "Write a pyproject.toml with optional dependencies and dependency groups",
            "Create a multi-stage Dockerfile that separates build dependencies from runtime with uv",
            "Write a Bash script that configures uv workspace for monorepo Python projects",
            "Create a Dockerfile that uses --system flag for containers without venv",
            "Write a CI script that persistently caches uv cache between builds",
        ],
    },
}


def get_domain_seeds(domain: str) -> list[str]:
    """Get seed instructions for a specific domain."""
    template = DOMAIN_TEMPLATES.get(domain)
    if template:
        return template.get("seeds", [])
    return []


def get_all_topics() -> list[str]:
    """Get all unique topics across all domains."""
    topics = set()
    for template in DOMAIN_TEMPLATES.values():
        topics.update(template.get("topics", []))
    return sorted(topics)


def get_domain_description(domain: str) -> str:
    """Get the description for a domain."""
    template = DOMAIN_TEMPLATES.get(domain)
    if template:
        return template.get("description", "")
    return ""


# =============================================================================
# Combined Domain + Role Functions
# =============================================================================


def get_all_templates() -> dict[str, dict[str, Any]]:
    """Get all templates (both domains and roles).

    Returns:
        Combined dictionary of domain and role templates
    """
    templates = DOMAIN_TEMPLATES.copy()
    templates.update(get_all_roles_as_domain_templates())
    return templates


def get_template_seeds(name: str) -> list[str]:
    """Get seeds from either a domain or a role.

    Args:
        name: Domain or role name

    Returns:
        List of seed instructions
    """
    # Try domains first
    seeds = get_domain_seeds(name)
    if seeds:
        return seeds

    # Try roles
    return get_role_seeds(name)


def get_template_choices() -> dict[str, list[str]]:
    """Get all template choices organized by category.

    Returns:
        Dictionary with categories as keys and lists of template names as values
    """
    choices = {
        "Technical Domains": list(DOMAIN_TEMPLATES.keys()),
    }

    # Add role categories
    role_manager = get_role_manager()
    for category in role_manager.get_categories():
        cat_name = category.get("name", "Other")
        roles = role_manager.get_roles_by_category(cat_name)
        if roles:
            choices[f"Roles: {cat_name}"] = [role.display_name for role in roles]

    return choices
